### ISSUE TITLE
i18n: add Occitan locale

### ISSUE THREAD

**Issue by Mejans** [mastodon/joinmastodon#309] opened 2023-02-06 10:00 UTC
Hello,
I finished the translation into Occitan on the Crowdin platform.
Would it be possible to add it to the web site?
Regards

**Comment by xmgz** [comment] 2023-04-04 03:36
locales have been updated here (2 months ago) but are not available in drop down menu for selection on joinmastodon.org 

some other translated languages (at 100%) are missing :(


thanks for open this issue.

**Comment by Mejans** [comment] 2023-05-29 15:58
Hello @Gargron would it be possible to have a look at this PR please?

**Comment by andypiper** [comment] 2023-12-10 12:53
Duplicate of #213

**Closed by andypiper** 2023-12-10 12:53 UTC
Labels: i18n
